#!/usr/bin/env bash
#
# Modified from https://github.com/holman/dotfiles/blob/master/script/bootstrap

cd "$(dirname "$0")"
DOTFILES_ROOT=$(pwd -P)

set -e -u

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

topic () {
  local src=$1
  local topic="${src#"$DOTFILES_ROOT"}"
  topic="${topic%.*}"
  topic="${topic:1}"
  topic="${topic/\// | }"
  echo "$topic"
}

run_all() {
  local script_ext=$1

  info "running $script_ext scripts"

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name "*.$script_ext")
  do
    if source $src
    then
      local topic=$(topic $src)
      success "($script_ext) $topic"
    else
      fail "error in $src"
    fi
  done
}

symlink () {
  info 'symlinking dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  link_file $DOTFILES_ROOT $HOME/.dotfiles

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

run_all 'before'
echo ''
symlink
echo ''
run_all 'after'
echo ''

echo '  All up-to-date!'
